### ISSUE TITLE
server.close() need a fix

### ISSUE THREAD

**Issue by FlorianBELLAZOUZ** [uWebSockets/uWebSockets#241]
Hi !

Frist, thanks for your awesome work !

I find an issue on the close function, after the close, the process continue to listen the port :

````js
var Wss = require('uws').Server
var wss = new Wss({port:8080})
setTimeout(()=>wss.close(),1000)
setTimeout(()=>wss = new Wss({port:8080}), 2000)

// 2 sec later 
// Error: listen EADDRINUSE :::8080
//    at Object.exports._errnoException (util.js:1026:11)
//    at exports._exceptionWithHostPort (util.js:1049:20)
//    at Server._listen2 (net.js:1253:14)
//    at listen (net.js:1289:10)
//    at Server.listen (net.js:1385:5)
//    at Server (C:\Users\florian\Main\modules\kaaalastic\node_modules\uws\uws.js:423:33)
//    at Timeout.setTimeout (repl:1:22)
//    at tryOnTimeout (timers.js:232:11)
//    at Timer.listOnTimeout (timers.js:202:5)
````

It's usefull when we unit test a websocket service to close and reopen on the same port.

**Comment by alexhultman** [comment]
What happens if you do the same with an http server?

**Comment by FlorianBELLAZOUZ** [comment]
Wow ! Thanks for your reactivity !

````js
var Http = require('http')

var serv = Http.createServer().listen(8080)

setTimeout(()=>{serv.close()},1000)
setTimeout(()=>{serv = Http.createServer().listen(8080)},2000)

// 2 sec later 
// no error
````

**Comment by alexhultman** [comment]
If you look in nodejs/dist/uws.js at the very bottom in the close function it's missing to close the http server. Can you add it and PR?
