### ISSUE TITLE
ssl websocket server 0.10.2  Registering more than one listener to a WebSocket is not supported.

### ISSUE THREAD

**Issue by arpu** [uWebSockets/uWebSockets#268]
node_modules/uws/uws.js:133
                throw Error(EE_ERROR);
                ^

Error: Registering more than one listener to a WebSocket is not supported.
    at Error (native)
    at WebSocket.on (/home/p2ph5/wsserver/node_modules/uws/uws.js:133:23)
    at Server.<anonymous> (/home/p2ph5/wsserver/server.js:127:6)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.handleUpgrade [as _upgradeCallback] (/home/p2ph5/wsserver/node_modules/uws/uws.js:368:34)
    at Server.native.server.group.onConnection (/home/p2ph5/wsserver/node_modules/uws/uws.js:406:18)
    at TLSSocket.socket.on (/home/p2ph5/wsserver/node_modules/uws/uws.js:429:24)
    at emitOne (events.js:101:20)
    at TLSSocket.emit (events.js:188:7)

**Comment by alexhultman** [comment]
Yep, it is not supported. This is a hint that you are doing something inefficient.

**Comment by arpu** [comment]
ok thx for this hint, i found the problem
