### ISSUE TITLE
App Crashes unexpectedly

### ISSUE THREAD

**Issue by chintan39** [uWebSockets/uWebSockets#306]
Form the logs I see the below error logs

  debug:MAIN: Caught exception:  +0ms
  debug:MAIN: TypeError: Cannot create property 'external' on number '0'
    at Server.native.server.group.onDisconnection (/home/xxxxxxxx/xxxxx/node_modules/uws/uws.js:396:32) +0ms
  debug:MAIN: TypeError: Cannot create property 'external' on number '0'
    at Server.native.server.group.onDisconnection (/home/xxxxxxxx/xxxxx/node_modules/uws/uws.js:396:32) +0ms

node: ../deps/uv/src/unix/poll.c:88: uv_poll_stop: Assertion `!(handle->flags & (UV_CLOSING | UV_CLOSED))' failed.
Aborted (core dumped)

P.S - I am using Ubuntu 16.04

**Comment by alexhultman** [comment]
You already reported this bug
