### ISSUE TITLE
uws crashes in node if send callback function is supplied

### ISSUE THREAD

**Issue by manuel-schiller** [uWebSockets/uWebSockets#311]
The following code crashes when sending a message after connecting to a websocket server:

```
var WebSocket = require("uws");
var ws = new WebSocket("ws://localhost:54321");

ws.on('open', function open() {
    ws.send("hello", function (error) {});
});
```

However, it works if the send callback is **not** supplied.
I am using uws 0.11 with node 4.6 on Linux, this is the backtrace of the crash:

```
Thread 1 "node" received signal SIGSEGV, Segmentation fault.
0x00007ffff7f97201 in sendCallback(void*, void*, bool) () from /tmp/node_modules/uws/uws_linux_46.node
(gdb) bt
#0  0x00007ffff7f97201 in sendCallback(void*, void*, bool) () from /tmp/node_modules/uws/uws_linux_46.node
#1  0x00007ffff7f92fbb in uWS::WebSocket<false>::send(char const*, unsigned long, uWS::OpCode, void (*)(void*, void*, bool), void*) ()
   from /tmp/node_modules/uws/uws_linux_46.node
#2  0x00007ffff7f9b520 in void send<false>(v8::FunctionCallbackInfo<v8::Value> const&) () from /tmp/node_modules/uws/uws_linux_46.node
#3  0x000000000067e91e in v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) ()
#4  0x00000000006a6d46 in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::(anonymous namespace)::BuiltinArguments<(v8::internal::BuiltinExtraArguments)1>&) ()
#5  0x00000000006a7313 in v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) ()
```

**Comment by alexhultman** [comment]
This is only for clients right? If you do the same with a server it should work.

**Comment by manuel-schiller** [comment]
I only tried it with the client API so far.

**Comment by alexhultman** [comment]
I cannot reproduce this. It works for me.

**Comment by alexhultman** [comment]
What server did you connect to?
