### ISSUE TITLE
Callback on verifyClient errors out

### ISSUE THREAD

**Issue by suchitagarwal** [uWebSockets/uWebSockets#326]
If I use the verifyClient option of WebSocketServer and call the callback method from inside a promise or another callback, the uwebsocket library errors out. The exact same code does not error out if I use ws instead.

Error:
```
   [ 'TypeError: Cannot read property \'fd\' of null',
     '    at Server.handleUpgrade (/Users/suchitagarwal/workspace/spokebot/node_modules/uws/uws.js:435:56)',
     '    at options.verifyClient (/Users/suchitagarwal/workspace/spokebot/node_modules/uws/uws.js:358:42)',
```

Sample verifyClient method:

```
  verifyClient(info, callback) {
     const userId = getUserIdFromInfo(info);
      User.findOne({_id: userId}, (err, user) => {
        callback(!!user);
      })
  },
```

**Comment by alexhultman** [comment]
Are you using windows?

**Comment by suchitagarwal** [comment]
No MacOSX 10.11.x
