### ISSUE TITLE
Compilation failed in Debian 8

### ISSUE THREAD

**Issue by soylomass** [uWebSockets/uWebSockets#327]
When I run a node.js script that requires uws in a brand new Debian 8 server, the following error appears:

> Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.

I editted the code to show the exception, which says:

> { Error: Cannot find module './uws_linux_51'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at native (/srv/www/deeeep.io/server-build/node_modules/uws/uws.js:15:20)
    at Object.<anonymous> (/srv/www/deeeep.io/server-build/node_modules/uws/uws.js:30:3)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12) code: 'MODULE_NOT_FOUND' }

I've searched for uws_linux_51 in google and nothing appears, so I ask here.

Thanks in advance.

**Comment by soylomass** [comment]
Ok, solved it with apt-get install build-essential and then deleting node_modules and installing again.
