### ISSUE TITLE
Missing classes/methods

### ISSUE THREAD

**Issue by zanaca** [uWebSockets/uWebSockets#482]
On Linux,  64bits,  v0.13.0, there are some default http methods missing from *uws* module.  The problem is not from Koa.

For example, I cannot access http.response.removeHeader function:
```javascript
TypeError: this.res.removeHeader is not a function
    at Object.remove (PROJECT/node_modules/koa/lib/response.js:476:14)
    at Object.set body [as body] (PROJECT/node_modules/koa/lib/response.js:174:10)
    at Object.body (PROJECT/node_modules/delegates/index.js:92:31)
    at Object.v2Get (PROJECT/src/controllers/search.js:468:18)
    at v2Get.next (<anonymous>)
    at Object.dispatch (PROJECT/node_modules/koa-router/lib/router.js:331:14)
    at dispatch.next (<anonymous>)
    at Object.compress (PROJECT/node_modules/koa-compress/index.js:42:12)
    at compress.next (<anonymous>)
    at onFulfilled (PROJECT/node_modules/co/index.js:65:19)
```

and removeHeader is from http Response class:
https://nodejs.org/api/http.html#http_response_removeheader_name

**Comment by Nicholaiii** [comment]
@alexhultman Why was this issue closed? I'm using 0.18.0 and it's still an issue.
