### ISSUE TITLE
Cannot attach http server to socket.io

### ISSUE THREAD

**Issue by andreimavenhut** [uWebSockets/uWebSockets#520]
Hi, 
I use uws 0.13 and i need to be able to have a https (uws server) and socket.io on the same port.
This is what i tried:

```
var http = require("uws").http;

var options = {
	key: fs.readFileSync('./file.pem'),
	cert: fs.readFileSync('./file.crt')
};

var server = http.createServer(options, function (req, res) {
	res.end('Welcome!');
});
server.listen(443, function() {
	console.log('server up and running at 443 port');
});
io = require('socket.io')(server);
```

And i get this error:
```
/app/socket/node_modules/engine.io/lib/server.js:424
  var listeners = server.listeners('request').slice(0);
                         ^
TypeError: server.listeners is not a function
    at Server.attach (/app/socket/node_modules/engine.io/lib/server.js:424:26)
    at Function.attach (/app/socket/node_modules/engine.io/lib/engine.io.js:124:10)
    at Server.listen.Server.attach (/app/socket/node_modules/socket.io/lib/index.js:240:21)
    at new Server (/app/socket/node_modules/socket.io/lib/index.js:52:17)
    at Server (/app/socket/node_modules/socket.io/lib/index.js:40:41)
    at Object.<anonymous> (/app/socket/test.js:21:27)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

Any ideas on how to fix this?

I need to be able to do https requests and also websockets connections. If i try 
```
server.listen(443, function() {
	console.log('server up and running at 443 port');
});
console.log(server)
```
the response is:
```
server up and running at 443 port
{}
```

**Comment by alexhultman** [comment]
This is not supported. You do the opposite - run the addon on the Node.js http server.
