### ISSUE TITLE
WebSocket.send() of very large string closes the WebSocket unexpectedly

### ISSUE THREAD

**Issue by oxygens** [uWebSockets/uWebSockets#584]
```shell
git clone git@github.com:oxygens/jsonrpc-bidirectional.git jsonrpc-bidirectional
cd jsonrpc-bidirectional
npm install
node --expose-gc --max-old-space-size=3072 tests/bug_uws_send_large_string_connection_closed.js
```

Windows 10, 64 bit

Works fine with `ws`.

```log

[20348] callRPCMethodSiteB
[20348] [2017-04-25T20:32:39.200Z] Sent JSONRPC request, ping(). Larger than 1 MB, not logging.

[20348] Rejecting all Promise instances in WebSockets/JSONRPCClientPlugin.
[20348] Rejecting all Promise instances in WebSockets/JSONRPCClientPlugin.
[20348] Rejected 1 Promise instances in WebSockets/JSONRPCClientPlugin.
[20348] Unhandled Rejection at: Promise Promise {
  <rejected> Error: WebSocket closed. Code: 1006. Message: ""
    at WebSocketWrapper._webSocket.on (C:\Users\oxygen\Desktop\jsonrpc-bidirectional\src\Plugins\Client\WebSocketTransport.js:197:29)
    at emitTwo (events.js:111:20)
    at WebSocketWrapper.emit (events.js:194:7)
    at WebSocketClient._webSocket.on.theArgs [as internalOnClose] (C:\Users\oxygen\Desktop\jsonrpc-bidirectional\src\WebSocketAdapters\uws\WebSocketWrapper.js:86:11)
    at process.nextTick (C:\Users\oxygen\Desktop\jsonrpc-bidirectional\node_modules\uws\uws.js:63:19)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9) } reason Error: WebSocket closed. Code: 1006. Message: ""
    at WebSocketWrapper._webSocket.on (C:\Users\oxygen\Desktop\jsonrpc-bidirectional\src\Plugins\Client\WebSocketTransport.js:197:29)
    at emitTwo (events.js:111:20)
    at WebSocketWrapper.emit (events.js:194:7)
    at WebSocketClient._webSocket.on.theArgs [as internalOnClose] (C:\Users\oxygen\Desktop\jsonrpc-bidirectional\src\WebSocketAdapters\uws\WebSocketWrapper.js:86:11)
    at process.nextTick (C:\Users\oxygen\Desktop\jsonrpc-bidirectional\node_modules\uws\uws.js:63:19)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by oxygens** [comment]
It is relatively easy to reproduce the issue with the given steps.

There's also a related issue: https://github.com/uWebSockets/uWebSockets/issues/534

**Comment by alexhultman** [comment]
I'll reopen when you have properly filled the template out.

**Comment by oxygens** [comment]
```JavaScript
const WebSocket = require("uws");
const WebSocketServer = WebSocket.Server;


(async () => {
	const webSocketServer = new WebSocketServer({port: 8080});
	webSocketServer.on("error", console.error);
	webSocketServer.on("connection", console.log);
	webSocketServer.on("message", console.log);


	
	const webSocket = new WebSocket("ws://localhost:8080/api");
	await new Promise((fnResolve, fnReject) => {
		webSocket.on("open", fnResolve);
		webSocket.on("error", fnReject);
	});

	let str10MBPayload = "";
	let nIterator = 0;
	while(str10MBPayload.length < 10 * 1024 * 1024 /*10 MB*/)
	{
		str10MBPayload += str10MBPayload + "_" + (++nIterator);
	}
	
	webSocket.on("close", process.exit);
	webSocket.send(str10MBPayload);
})();
```

There.

**Comment by alexhultman** [comment]
Right, you see I have a template to fill out so that I can early catch what the user is doing.

You have several issues in your code:

* You are actually sending more than 16 mb, which is why the server terminates the connection as is the design.
* You are not even registering to the message events of the server properly. You don't have a "message" event on the server, you have it on the websockets the server creates.

**Comment by oxygens** [comment]
This is a message event on the server: 	`webSocketServer.on("message", console.log);`
It also should be irrelevant if a message event is registered on the server or not.

_"which is why the server terminates the connection as is the design."_
I will not argue with your design, yet you should properly document these things and __send a proper reason for closing the connection__ (currently an empty string is sent).

The code works with no issues with `ws`.
It doesn't matter how much I'm sending, your server closes a connection without specifying a reason.

"By design" means your design, or official spec?

**Comment by alexhultman** [comment]
Clearly the Autobahn test suite is wrong when it shows µWS 100% compliant. I would suggest opening an issue in their repo so that you can share your standards expertise with the world.

**Comment by oxygens** [comment]
The connection close reason parameter is there for ... a reason. And the reason is: help developers find out why the connection was closed so they can debug.

Clearly the Autobahn is not testing for this scenario, and clearly it doesn't care about the connection close reason beeing an empty string.

And clearly you don't care either, and you're arrogant beyond hope.

See ya.

**Comment by alexhultman** [comment]
I'm sorry, let me lube up my asshole real good so that you can go deep, deep inside while I fix your mistakes for free.

**Comment by oxygens** [comment]
Dude, the only mistake is that you have lube in your eyes.

I repeat: there is a message handler on the server.

And you're sloppy: you're closing the connection with an empty string as reason. Must be because of all that lube on your hands.

**Comment by alexhultman** [comment]
Yes I need to lube up real good to enter your dried up mother you see.
