### ISSUE TITLE
Error when using with with Node.js Compiler

### ISSUE THREAD

**Issue by chintan39** [uWebSockets/uWebSockets#595]
Node compiler (https://github.com/pmq20/node-compiler) makes a single executable for Node.js app

"Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'"
at native (/__enclose_io_memfs__/node_modules/uws/uws.js:38:19)
    at Object.<anonymous> (/__enclose_io_memfs__/node_modules/uws/uws.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/__enclose_io_memfs__/main.js:11:23)

**Comment by alexhultman** [comment]
There are about 54 of these projects and they all make naive assumptions that break the Node.js addon scene. It's an issue in respective packager (nexe, node-compiler, pkg, webpack, insdrt bullshit project here, etc). If they want to make a packager they need to figure out how not to break the industry.

**Comment by chintan39** [comment]
Okay, I just reported it because only "uws" was broken, when I ran the final executable.
May be I don't have other native addons, will try with "ws" once too

**Comment by alexhultman** [comment]
node-compiler doesn't even support addons: https://github.com/pmq20/node-compiler/issues/25

Why am I doing your research for you?
